require: rubocop-rspec

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

RSpec/MultipleMemoizedHelpers:
  Max: 13

RSpec/DescribedClass:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

AllCops:
  NewCops: enable
  SuggestExtensions: false
   
