require: rubocop-rspec

Style/Documentation:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

AllCops:
  NewCops: enable
  SuggestExtensions: false
   
