require: rubocop-rspec

Style/Documentation:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - 'spec/cli_spec.rb'

AllCops:
  NewCops: enable
  SuggestExtensions: false
   
